import { createClient } from '@supabase/supabase-js';
import { redirect } from 'next/navigation';
import { AuditResults } from '@/components/AuditResults';
import { resolveServerSupabaseKey, resolveServerSupabaseUrl } from '@/lib/supabase/env';

interface PageParams {
  token: string;
}

export default async function PublicAuditPage(props: { params: Promise<PageParams> }) {
  const params = await props.params;

  // Use service role client for public access (bypass RLS)
  const supabase = createClient(
    resolveServerSupabaseUrl(),
    resolveServerSupabaseKey()
  );

  const { data: audit, error } = await supabase
    .from('audit_reports')
    .select('*')
    .eq('public_token', params.token)
    .eq('is_public', true)
    .single();

  if (error || !audit) {
    redirect('/audit/not-found');
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-black py-12 px-4">
      <div className="max-w-4xl mx-auto space-y-6">
        {/* Header */}
        <div className="text-center space-y-2">
          <h1 className="text-4xl font-bold text-white">Website Audit Report</h1>
          <p className="text-slate-400">Professional analysis powered by Agency Ops Suite</p>
        </div>

        {/* Results */}
        <div className="rounded-lg border border-white/10 bg-white/5 p-8">
          <AuditResults audit={audit} />
        </div>

        {/* Footer */}
        <div className="rounded-lg border border-white/10 bg-white/5 p-6 text-center text-sm text-slate-400">
          <p>Generated by <a href="/" className="text-accent-400 hover:text-accent-300">Agency Ops Suite</a> • {new Date(audit.generated_at).toLocaleDateString()}</p>
        </div>
      </div>
    </div>
  );
}
